server:
  port: 8081
  servlet:
    context-path: /con
dubbo:
  #??????
  application:
    name: zhuifeng-controller
  registry:
    address: zookeeper://127.0.0.1:2181
spring:
  freemarker:
    suffix: .ftl

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zhuifeng.shipping.pojo
  base-package: com.zhuifeng.shipping.web