logging:
  file:
    path: logs/demo.log
  level.org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shipping?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: wtq123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: zhuifeng-itinerary
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20882
    name: dubbo
server:
  port: 8082
  servlet:
    context-path: /itin
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zhuifeng.shipping.pojo
