#日志文件
logging:
  file:
    path: logs/demo.log
  level.org.springframework.web: DEBUG
  #数据库连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shipping?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: wtq123
    driver-class-name: com.mysql.jdbc.Driver
    #hikari数据库连接池
#    hikari:
#      pool-name: Retail_HikariCP
#        minimum-idle: 5 #最小空闲连接数量
#        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
#        maximum-pool-size: 10 #连接池最大连接数，默认是10
#        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
#        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
#        connection-test-query: SELECT 1
dubbo:
  application:
    name: zhuifeng-itinerary
  registry:
    address: zookeeper://127.0.0.1:2181
    #暴露端口
  protocol:
    port: 20882
    name: dubbo
server:
  port: 8082
  servlet:
    context-path: /itin
